修改 lint的实现形式

diff --git a/eslinthook b/eslinthook
--- a/eslinthook
+++ b/eslinthook
@@ -1,56 +1,50 @@
-#!/bin/sh
+#!/bin/bash
 
-jsfiles=$(git diff --cached --name-only --diff-filter=ACM  | grep "\.js$")
-vuefiles=$(git diff --cached --name-only --diff-filter=ACM  | grep "\.vue$")
+HAS_NODE=`which node 2> /dev/null || which nodejs 2> /dev/null || which iojs 2> /dev/null`
 
-echo "$jsfiles"
-echo "$vuefiles"
+#
+# There are some issues with Source Tree because paths are not set correctly for
+# the given environment. Sourcing the bash_profile seems to resolve this for bash users,
+# sourcing the zshrc for zshell users.
+#
+# https://answers.atlassian.com/questions/140339/sourcetree-hook-failing-because-paths-don-t-seem-to-be-set-correctly
+#
+function source_home_file {
+  file="$HOME/$1"
+  [[ -f "${file}" ]] && source "${file}"
+}
 
-
-# 若没有相关文件 直接退出
-if [ "$jsfiles" = "" &&  "$vuefiles" = ""]; then
-  exit 0
+if [[ -z "$HAS_NODE" ]]; then
+  source_home_file ".bash_profile" || source_home_file ".zshrc" || source_home_file ".bashrc" || true
 fi
 
+NODE=`which node 2> /dev/null`
+NODEJS=`which nodejs 2> /dev/null`
+IOJS=`which iojs 2> /dev/null`
+LOCAL="/usr/local/bin/node"
+BINARY=
 
-pass=true
+#
+# Figure out which binary we need to use for our script execution.
+#
+if [[ -n "$NODE" ]]; then
+  BINARY="$NODE"
+elif [[ -n "$NODEJS" ]]; then
+  BINARY="$NODEJS"
+elif [[ -n "$IOJS" ]]; then
+  BINARY="$IOJS"
+elif [[ -x "$LOCAL" ]]; then
+  BINARY="$LOCAL"
+fi
 
-echo "Validating JavaScript:"
-
-ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
-
-for file in ${jsfiles}; do
-    echo "------------------------------------------------------"
-    result=$(${ESLINT} ${file} | grep "error")
-    echo "$result"
-    if [ "$result" == "" ]; then
-        echo "ESLint Passed: ${file}"
-    else
-        echo "ESLint Failed: ${file}"
-        pass=false
-    fi
-    echo "------------------------------------------------------"
-done;
-
-for file in ${vuefiles}; do
-    echo "------------------------------------------------------"
-    result=$(${ESLINT} ${file} | grep "error")
-    echo "$result"
-    if [ "$result" == "" ]; then
-        echo "ESLint Passed: ${file}"
-    else
-        echo "ESLint Failed: ${file}"
-        pass=false
-    fi
-    echo "------------------------------------------------------"
-done;
-
-
-echo "JavaScript validation complete:"
-
-if ! $pass; then
-    echo "commit [filed]"
+#
+# Add --dry-run cli flag support so we can execute this hook without side affects
+# and see if it works in the current environment
+#
+if [[ $* == *--dry-run* ]]; then
+  if [[ -z "$BINARY" ]]; then
     exit 1
+  fi
 else
-    echo "commit [success]"
+  "$BINARY" "$("$BINARY" -e "console.log(require.resolve('pre-commit'))")"
 fi
